# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-08-02 23:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0035_auto_20200801_1730'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comunicacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('tipo', models.SmallIntegerField(choices=[(1, 'cobrança'), (2, 'aniversário'), (3, 'avisos'), (4, 'conteúdo'), (5, 'outros')])),
                ('meio', models.SmallIntegerField(choices=[(1, 'email'), (2, 'sms'), (3, 'whatsApp'), (4, 'msg_aplicativo'), (5, 'carta'), (6, 'telefone')])),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.Escola')),
            ],
            options={
                'ordering': ('-data',),
            },
        ),
        migrations.CreateModel(
            name='PessoaMensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_id', models.IntegerField(blank=True, null=True, verbose_name='ID do contrato')),
                ('email', models.EmailField(max_length=254, verbose_name='email do destinatário')),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Lida em: ')),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunicacao.Mensagem')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.Pessoa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='mensagemdefault',
            name='tipo',
            field=models.SmallIntegerField(choices=[(1, 'cobrança'), (2, 'aniversário'), (3, 'avisos'), (4, 'conteúdo'), (5, 'outros')], verbose_name='Tipo:'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='pessoas',
            field=models.ManyToManyField(through='comunicacao.PessoaMensagem', to='escolas.Pessoa'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
