# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2021-01-10 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacao', '0002_auto_20200802_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoamensagem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
