# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('endereco', models.CharField(max_length=200, verbose_name='endereço')),
                ('numero', models.CharField(max_length=10, verbose_name='número')),
                ('telefone', models.CharField(blank=True, max_length=14, null=True, verbose_name='telefone')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='comnplemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='bairro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('slug', models.CharField(max_length=50, null=True, verbose_name='slug')),
                ('site', models.URLField(blank=True, null=True, verbose_name='website')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name_plural': 'escolas',
                'verbose_name': 'escola',
            },
        ),
    ]
