# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 23:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(choices=[(2017, 2017), (2018, 2018)], verbose_name='Ano')),
                ('curso', models.CharField(max_length=50)),
                ('periodo', models.SmallIntegerField(blank=True, choices=[(1, 'Manhã'), (2, 'Tarde'), (3, 'Noite')], null=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.Escola')),
            ],
        ),
        migrations.CreateModel(
            name='ClasseAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='ClasseProfessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=80)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.Classe')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='classeprofessor',
            unique_together=set([('classe', 'professor', 'materia')]),
        ),
        migrations.AlterUniqueTogether(
            name='classealuno',
            unique_together=set([('classe', 'aluno')]),
        ),
    ]
