# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-18 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0002_grupo_grupouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='nome',
            field=models.CharField(default='name', max_length=80, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together=set([('nome', 'escola')]),
        ),
    ]
