# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 00:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escolas', '0002_auto_20170201_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='email')),
                ('celular', models.CharField(max_length=14, verbose_name='celular')),
                ('documento', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutorizadoAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de cadastro')),
                ('status', models.BooleanField(default=False, verbose_name='Ativo')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL)),
                ('autorizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.Autorizado')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.Escola')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['-ano']},
        ),
        migrations.AlterModelOptions(
            name='classealuno',
            options={'ordering': ['aluno__nome']},
        ),
        migrations.AlterField(
            model_name='classe',
            name='ano',
            field=models.SmallIntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018)], verbose_name='Ano'),
        ),
    ]
