# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pais'),
        ('escolas', '0003_auto_20170228_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Pais'),
            preserve_default=False,
        ),
    ]
