# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0005_responsavelaluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d'),
        ),
    ]
