# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-11 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import escolar.escolas.models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0006_auto_20170413_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='publica',
            field=models.BooleanField(default=False, verbose_name='Escola pública'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=escolar.escolas.models.escola_directory_path),
        ),
    ]
