# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-16 22:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0007_auto_20171211_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizadoaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizados_aluno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='responsavelaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responseveis_aluno', to=settings.AUTH_USER_MODEL),
        ),
    ]
