# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-12 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0007_auto_20171205_0014'),
        ('escolas', '0007_auto_20171211_2350'),
    ]

    operations = [
    ]
