# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-02 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0008_auto_20171216_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='ano',
            field=models.SmallIntegerField(choices=[(2017, 2017), (2018, 2018), (2019, 2019)], verbose_name='Ano'),
        ),
    ]
