# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-02 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0009_auto_20180102_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavelaluno',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='responsavelaluno',
            name='escola',
        ),
        migrations.RemoveField(
            model_name='responsavelaluno',
            name='responsavel',
        ),
        migrations.DeleteModel(
            name='ResponsavelAluno',
        ),
    ]
