# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-21 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0009_merge'),
        ('escolas', '0011_auto_20180118_0134'),
    ]

    operations = [
    ]