# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-26 01:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import escolar.escolas.models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
        ('core', '0003_auto_20180118_0134'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escolas', '0012_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_upd', models.DateTimeField(default=django.utils.timezone.now)),
                ('ano', models.SmallIntegerField(default=2018)),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=14, null=True, verbose_name='RG')),
                ('nacionalidade', models.CharField(max_length=50)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to=escolar.escolas.models.escola_aluno_directory_path, verbose_name='RG e ou CPF')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=escolar.escolas.models.escola_aluno_directory_path, verbose_name='Foto')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Endereco')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.Escola')),
                ('natural_municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipios.Municipio')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolas_aluno_created_by', to=settings.AUTH_USER_MODEL)),
                ('user_upd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolas_aluno_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='MembroFamilia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_upd', models.DateTimeField(default=django.utils.timezone.now)),
                ('parentesco', models.CharField(max_length=100)),
                ('responsavel_financeiro', models.BooleanField(default=False)),
                ('responsavel_pedagogico', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=100)),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
                ('profissao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
                ('sexo', models.SmallIntegerField(verbose_name='Sexo')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=14, null=True, verbose_name='RG')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('empresa', models.CharField(max_length=100)),
                ('telefone_empresa', models.CharField(max_length=11)),
                ('obs_empresa', models.CharField(max_length=100)),
                ('documento', models.FileField(blank=True, null=True, upload_to=escolar.escolas.models.escola_aluno_parente_directory_path, verbose_name='RG e ou CPF')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.Aluno')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolas_membrofamilia_created_by', to=settings.AUTH_USER_MODEL)),
                ('user_upd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolas_membrofamilia_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
