# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-31 00:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0015_auto_20180128_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizadoaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.Aluno'),
        ),
        migrations.AlterField(
            model_name='autorizadoaluno',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
