# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-04 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0016_auto_20180131_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='celular',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='ra',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='RA'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='sexo',
            field=models.SmallIntegerField(default=2, verbose_name='Sexo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
