# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-13 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
        ('escolas', '0017_auto_20180204_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='municipio',
            field=models.ForeignKey(default=3549904, on_delete=django.db.models.deletion.CASCADE, to='municipios.Municipio'),
            preserve_default=False,
        ),
    ]
