# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-19 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0018_escola_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrofamilia',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membrofamilia',
            name='obs_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membrofamilia',
            name='telefone_empresa',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
