# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-25 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0019_auto_20180218_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membrofamilia',
            name='aluno',
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsaveis',
            field=models.ManyToManyField(to='escolas.MembroFamilia'),
        ),
    ]
