# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0020_auto_20180225_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ra',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RA'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, null=True, to='escolas.MembroFamilia'),
        ),
    ]
