# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0021_auto_20180225_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='cnpj',
            field=models.CharField(default='01626645000105', max_length=14, verbose_name='cnp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escola',
            name='razao_social',
            field=models.CharField(default='Crescer Espaço de Crescimento e Aperfeiçoamento Psicopedagógico S/C Ltda', max_length=200, verbose_name='razão social'),
            preserve_default=False,
        ),
    ]
