# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0022_auto_20180302_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serie',
            options={'ordering': ('id',), 'verbose_name': 'série', 'verbose_name_plural': 'séries'},
        ),
    ]
