# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-14 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0023_auto_20180309_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(blank=True, max_length=100, null=True)),
                ('responsavel_financeiro', models.BooleanField(default=False)),
                ('responsavel_pedagogico', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.Aluno')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.MembroFamilia')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
            },
        ),
    ]
