# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-14 23:38
from __future__ import unicode_literals

from django.db import migrations

def set_responsaveis(apps, schema_editor):
    '''
    ref #61
    '''
    Aluno = apps.get_model('escolas', 'Aluno')
    Responsavel = apps.get_model('escolas', 'Responsavel')
    criados = []
    for aluno in Aluno.objects.all():
        for membro in aluno.responsaveis.all():
            resp, created = Responsavel.objects.update_or_create(aluno=aluno,
                                                                 membro=membro,
                                                                 parentesco=membro.parentesco,
                                                                 responsavel_financeiro=membro.responsavel_financeiro,
                                                                 responsavel_pedagogico=membro.responsavel_pedagogico)
            criados.append(created)
    print(criados)


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0024_responsavel'),
    ]

    operations = [
        migrations.RunPython(set_responsaveis),
    ]
