# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-18 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0025_auto_20180314_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='responsaveis',
        ),
    ]
