# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-08 03:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import escolar.escolas.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('municipios', '0001_initial'),
        ('core', '0007_auto_20180309_2232'),
        ('escolas', '0026_remove_aluno_responsaveis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_upd', models.DateTimeField(default=django.utils.timezone.now)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('documento', models.FileField(blank=True, null=True, upload_to=escolar.escolas.models.escola_aluno_directory_path, verbose_name='RG e ou CPF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('nacionalidade', models.CharField(max_length=50)),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
                ('nome', models.CharField(max_length=100)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
                ('rg', models.CharField(blank=True, max_length=14, null=True, verbose_name='RG')),
                ('sexo', models.SmallIntegerField(verbose_name='Sexo')),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsavelEscola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(blank=True, max_length=100, null=True)),
                ('responsavel_financeiro', models.BooleanField(default=False)),
                ('responsavel_pedagogico', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
            },
        ),
        migrations.AlterField(
            model_name='aluno',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to=escolar.escolas.models.escola_aluno_directory_path, verbose_name='RG e ou CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=escolar.escolas.models.escola_aluno_directory_path, verbose_name='Foto'),
        ),
        migrations.CreateModel(
            name='AlunoEscola',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='escolas.Pessoa')),
                ('ano', models.SmallIntegerField(default=2018)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=escolar.escolas.models.escola_aluno_directory_path, verbose_name='Foto')),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('ra', models.CharField(blank=True, max_length=20, null=True, verbose_name='RA')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escolas.Curso')),
            ],
            options={
                'abstract': False,
            },
            bases=('escolas.pessoa',),
        ),
        migrations.CreateModel(
            name='MembroFamiliaEscola',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='escolas.Pessoa')),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('obs_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('parentesco', models.CharField(max_length=100)),
                ('responsavel_financeiro', models.BooleanField(default=False)),
                ('responsavel_pedagogico', models.BooleanField(default=False)),
                ('telefone_empresa', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('escolas.pessoa',),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Endereco'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.Escola'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='natural_municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipios.Municipio'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='user_add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolas_pessoa_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='user_upd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolas_pessoa_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsavelescola',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.AlunoEscola'),
        ),
        migrations.AddField(
            model_name='responsavelescola',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.MembroFamiliaEscola'),
        ),
    ]
