# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-08 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0027_auto_20180408_0042'),
    ]

    operations = [
    	migrations.RenameModel("Aluno", "AlunoDeprecated"),
    	migrations.RenameModel("AlunoEscola", "Aluno"),
    	migrations.RenameModel("MembroFamilia", "MembroFamiliaDeprecated"),
    	migrations.RenameModel("MembroFamiliaEscola", "MembroFamilia"),
    	migrations.RenameModel("Responsavel", "ResponsavelDeprecated"),
    	migrations.RenameModel("ResponsavelEscola", "Responsavel")
    ]
