# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-06 02:08
from __future__ import unicode_literals

from django.db import migrations


def set_pessoa(apps, schema_editor):
    '''
    ref #61
    '''
    Escola = apps.get_model('escolas', 'Escola')
    Aluno = apps.get_model('escolas', 'Aluno')
    MembroFamilia = apps.get_model('escolas', 'MembroFamilia')
    Pessoa = apps.get_model('escolas', 'Pessoa')
    escola = Escola.objects.get(id=1)
    criados = []
    for aluno in Aluno.objects.all():
        pessoa, created = Pessoa.objects.update_or_create(date_add=aluno.date_add,
                                                          date_upd=aluno.date_upd,
                                                          user_add=aluno.user_add,
                                                          user_upd=aluno.user_upd,
                                                          celular=aluno.celular,
                                                          cpf=aluno.cpf,
                                                          documento=aluno.documento,
                                                          email=aluno.email,
                                                          endereco=aluno.endereco,
                                                          escola=aluno.escola,
                                                          nacionalidade='Brasileira',
                                                          nascimento=aluno.nascimento,
                                                          natural_municipio=aluno.natural_municipio,
                                                          nome=aluno.nome,
                                                          profissao=aluno.profissao,
                                                          rg=aluno.rg,
                                                          sexo=aluno.sexo,
                                                          telefone=aluno.telefone,
                                                          user=aluno.user)
        criados.append(created)
        if created:
            aluno.pessoa = pessoa
            aluno.save()
    print('Pessoas, alunos criados', criados)


    for membro in MembroFamilia.objects.all():
        pessoa, created = Pessoa.objects.update_or_create(date_add=membro.date_add,
                                                          date_upd=membro.date_upd,
                                                          user_add=membro.user_add,
                                                          user_upd=membro.user_upd,
                                                          celular=membro.celular,
                                                          cpf=membro.cpf,
                                                          documento=membro.documento,
                                                          email=membro.email,
                                                          escola=escola,
                                                          nacionalidade='Brasileira',
                                                          nascimento=membro.nascimento,
                                                          nome=membro.nome,
                                                          profissao=membro.profissao,
                                                          rg=membro.rg,
                                                          sexo=membro.sexo,
                                                          telefone=membro.telefone,
                                                          user=membro.user)
        criados.append(created)
        if created:
            membro.pessoa = pessoa
            membro.save()

class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0027_auto_20180405_2300'),
    ]

    operations = [
        migrations.RunPython(set_pessoa),
    ]
