# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-11 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0028_auto_20180408_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunodeprecated',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='alunodeprecated',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='alunodeprecated',
            name='escola',
        ),
        migrations.RemoveField(
            model_name='alunodeprecated',
            name='natural_municipio',
        ),
        migrations.RemoveField(
            model_name='alunodeprecated',
            name='user',
        ),
        migrations.RemoveField(
            model_name='alunodeprecated',
            name='user_add',
        ),
        migrations.RemoveField(
            model_name='alunodeprecated',
            name='user_upd',
        ),
        migrations.RemoveField(
            model_name='membrofamiliadeprecated',
            name='user',
        ),
        migrations.RemoveField(
            model_name='membrofamiliadeprecated',
            name='user_add',
        ),
        migrations.RemoveField(
            model_name='membrofamiliadeprecated',
            name='user_upd',
        ),
        migrations.RemoveField(
            model_name='responsaveldeprecated',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='responsaveldeprecated',
            name='membro',
        ),
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ('nome',), 'verbose_name': 'aluno', 'verbose_name_plural': 'alunos'},
        ),
        migrations.AlterModelOptions(
            name='membrofamilia',
            options={'ordering': ('nome',), 'verbose_name': 'Membro da Família', 'verbose_name_plural': 'Membros da Família'},
        ),
        migrations.AlterField(
            model_name='autorizadoaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.Aluno'),
        ),
        migrations.DeleteModel(
            name='AlunoDeprecated',
        ),
        migrations.DeleteModel(
            name='MembroFamiliaDeprecated',
        ),
        migrations.DeleteModel(
            name='ResponsavelDeprecated',
        ),
    ]
