# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-06 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0028_auto_20180405_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='id',
        ),
        migrations.RemoveField(
            model_name='membrofamilia',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='teste',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='escolas.Pessoa'),
        ),
        migrations.AlterField(
            model_name='membrofamilia',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='escolas.Pessoa'),
        ),
    ]
