# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-07 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0029_auto_20180405_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='escola',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='natural_municipio',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='user_add',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='user_upd',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='membrofamilia',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='aluno',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membrofamilia',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
