# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 00:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escolas', '0030_auto_20180412_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=500)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.Aluno')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-data',),
            },
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ('nome',), 'verbose_name': 'pessoa', 'verbose_name_plural': 'pessoas'},
        ),
    ]
