# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0031_auto_20180419_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ('curso', 'nome'), 'verbose_name': 'aluno', 'verbose_name_plural': 'alunos'},
        ),
        migrations.AddField(
            model_name='autorizado',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='celular',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='email'),
        ),
    ]
