# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0032_auto_20180501_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='ano',
            field=models.SmallIntegerField(choices=[(None, '--'), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], verbose_name='Ano'),
        ),
    ]
