# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0033_auto_20180502_2317'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='responsavel',
            unique_together=set([('aluno', 'membro')]),
        ),
    ]
