# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2021-01-10 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0035_auto_20200801_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ano',
            field=models.SmallIntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escolas.Curso'),
        ),
        migrations.AlterField(
            model_name='alunohistorico',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classe',
            name='ano',
            field=models.SmallIntegerField(choices=[(None, '--'), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='municipios.Municipio'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Pais'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Endereco'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='natural_municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='municipios.Municipio'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serie',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escolas.Curso'),
        ),
    ]
