# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-12-27 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import escolar.sites.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escolas', '0035_auto_20200801_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=30, verbose_name='Chave')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Título')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=escolar.sites.models.escola_site_directory_path, verbose_name='Foto')),
                ('link', models.URLField(blank=True, null=True, verbose_name='link')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.Escola')),
            ],
        ),
    ]
