# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-12-31 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteudo',
            options={'ordering': ('ordem',)},
        ),
        migrations.AddField(
            model_name='conteudo',
            name='ordem',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Ordem'),
        ),
    ]
