# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=3, verbose_name='Sigla')),
                ('idioma', models.CharField(blank=True, max_length=50, null=True, verbose_name='Idioma')),
            ],
        ),
    ]
