# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-13 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
        ('core', '0003_auto_20180118_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('name', models.CharField(max_length=100)),
                ('type_name', models.CharField(max_length=80)),
                ('type_code', models.SmallIntegerField(verbose_name='tipo')),
                ('uf_ibge_code', models.SmallIntegerField(blank=True, null=True, verbose_name='uf ibge')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipios.Municipio')),
            ],
            options={
                'verbose_name': 'Feriado',
            },
        ),
    ]
