# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 01:22
from __future__ import unicode_literals

from django.db import migrations


def set_username(apps, schema_editor):
    '''
    ref #59
    '''
    User = apps.get_model('core', 'User')
    for user in User.objects.all():
        user.username = user.email
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_username'),
    ]

    operations = [
    	migrations.RunPython(set_username),
    ]
