# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180309_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='teste', max_length=100, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
