# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2021-01-10 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180309_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='municipios.Municipio'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Perfil'),
        ),
        migrations.AlterField(
            model_name='feriado',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='municipios.Municipio'),
        ),
    ]
