-- CREATE TABLE "FORNECEDOR" -----------------------------------
CREATE TABLE [dbo].[FORNECEDOR] ( 
    [COD_FORNECEDOR] INT NOT NULL, 
    [NOM_FORNECEDOR] VARCHAR( 100 ) NOT NULL, 
    [NUM_CNPJ] NUMERIC NULL, 
    [DSC_ENDERECO] VARCHAR( 1000 ) NOT NULL, 
    [NUM_TELEFONE] NUMERIC NOT NULL,
    PRIMARY KEY ( [COD_FORNECEDOR] ), 
    CONSTRAINT [unique_COD_FORNECEDOR] UNIQUE ( [COD_FORNECEDOR] ) )
GO;
-- CREATE TABLE "SERVICO" --------------------------------------
CREATE TABLE [dbo].[SERVICO] ( 
    [COD_SERVICO] INT NOT NULL, 
    [COD_FORNECEDOR] INT NOT NULL, 
    [DSC_SERVICO] VARCHAR( 500 ) NOT NULL, 
    [TIP_SERVICO] VARCHAR( 50 ) NOT NULL, 
    [VLR_SERVICO] NUMERIC (10,2) NOT NULL,
    PRIMARY KEY ( [COD_SERVICO] ), 
    CONSTRAINT [unique_COD_SERVICO] UNIQUE ( [COD_SERVICO] ) )
GO;
-- CREATE INDEX "index_COD_FORNECEDOR" -------------------------
CREATE  INDEX [index_COD_FORNECEDOR] ON [dbo].[SERVICO]( [COD_FORNECEDOR] )
GO;
-- CREATE TABLE "ITEM_PEDIDO" ----------------------------------
CREATE TABLE [dbo].[ITEM_PEDIDO] ( 
    [NUM_PEDIDO] INT NOT NULL, 
    [COD_ITEM_PEDIDO] INT NOT NULL, 
    [COD_SERVICO] INT NOT NULL, 
    [QTD_SERVICO] NUMERIC NOT NULL, 
    [VLR_TOTAL_ITEM] NUMERIC (10,2) NOT NULL,
    PRIMARY KEY ( [COD_ITEM_PEDIDO] ) )
GO;
-- CREATE INDEX "index_NUM_PEDIDO" -----------------------------
CREATE  INDEX [index_NUM_PEDIDO] ON [dbo].[ITEM_PEDIDO]( [NUM_PEDIDO] )
GO;
-- CREATE TABLE "CLIENTE" --------------------------------------
CREATE TABLE [dbo].[CLIENTE] ( 
    [COD_CLIENTE] INT NOT NULL, 
    [NOM_CLIENTE] VARCHAR( 100 ) NOT NULL, 
    [NUM_CPF_CNPJ] NUMERIC DEFAULT '15' NULL, 
    [DSC_ENDERECO_COBRANCA] VARCHAR( 1000 ) NOT NULL, 
    [NUM_TELEFONE] NUMERIC DEFAULT '14' NOT NULL,
    PRIMARY KEY ( [COD_CLIENTE] ), 
    CONSTRAINT [unique_COD_CLIENTE] UNIQUE ( [COD_CLIENTE] ) )
GO;
-- CREATE TABLE "FORMA_PAGAMENTO" ------------------------------
CREATE TABLE [dbo].[FORMA_PAGAMENTO] ( 
    [COD_FORMA_PAGAMENTO] INT NOT NULL, 
    [DSC_FORMA_PAGAMENTO] VARCHAR( 100 ) NOT NULL,
    PRIMARY KEY ( [COD_FORMA_PAGAMENTO] ), 
    CONSTRAINT [unique_COD_FORMA_PAGAMENTO] UNIQUE ( [COD_FORMA_PAGAMENTO] ) )
GO;
-- CREATE TABLE "PEDIDO" ---------------------------------------
CREATE TABLE [dbo].[PEDIDO] ( 
    [NUM_PEDIDO] INT NOT NULL, 
    [COD_CLIENTE] INT NOT NULL, 
    [DAT_PEDIDO] DATETIME NOT NULL, 
    [VLR_TOTAL_PEDIDO] NUMERIC (10,2) NULL, 
    [COD_FORMA_PAGAMENTO] INT NOT NULL,
    PRIMARY KEY ( [NUM_PEDIDO] ), 
    CONSTRAINT [unique_NUM_PEDIDO] UNIQUE ( [NUM_PEDIDO] ) )
GO;
-- CREATE LINK "lnk_FORNECEDOR_SERVICO" ------------------------
ALTER TABLE [dbo].[SERVICO]
    ADD CONSTRAINT [lnk_FORNECEDOR_SERVICO]
    FOREIGN KEY ([COD_FORNECEDOR])
    REFERENCES [dbo].[FORNECEDOR]( [COD_FORNECEDOR] )
    ON DELETE Cascade
    ON UPDATE Cascade
GO;
-- -------------------------------------------------------------
-- CHANGE "ENABLED" OF "LINK "lnk_FORNECEDOR_SERVICO" ----------
ALTER TABLE [dbo].[SERVICO] NOCHECK CONSTRAINT [lnk_FORNECEDOR_SERVICO]
GO;
-- -----
-- CREATE LINK "lnk_SERVICO_ITEM_PEDIDO" -----------------------
ALTER TABLE [dbo].[ITEM_PEDIDO]
    ADD CONSTRAINT [lnk_SERVICO_ITEM_PEDIDO]
    FOREIGN KEY ([COD_SERVICO])
    REFERENCES [dbo].[SERVICO]( [COD_SERVICO] )
    ON DELETE Cascade
    ON UPDATE Cascade
GO;
-- -------------------------------------------------------------

-- CHANGE "ENABLED" OF "LINK "lnk_SERVICO_ITEM_PEDIDO" ---------
ALTER TABLE [dbo].[ITEM_PEDIDO] NOCHECK CONSTRAINT [lnk_SERVICO_ITEM_PEDIDO]
GO;
-- CREATE LINK "lnk_PEDIDO_ITEM_PEDIDO" ------------------------
ALTER TABLE [dbo].[ITEM_PEDIDO]
    ADD CONSTRAINT [lnk_PEDIDO_ITEM_PEDIDO]
    FOREIGN KEY ([NUM_PEDIDO])
    REFERENCES [dbo].[PEDIDO]( [NUM_PEDIDO] )
    ON DELETE Cascade
    ON UPDATE Cascade
GO;
-- -------------------------------------------------------------
-- CHANGE "ENABLED" OF "LINK "lnk_PEDIDO_ITEM_PEDIDO" ----------
ALTER TABLE [dbo].[ITEM_PEDIDO] NOCHECK CONSTRAINT [lnk_PEDIDO_ITEM_PEDIDO]
GO;
-- CREATE LINK "lnk_CLIENTE_PEDIDO" ----------------------------
ALTER TABLE [dbo].[PEDIDO]
    ADD CONSTRAINT [lnk_CLIENTE_PEDIDO]
    FOREIGN KEY ([COD_CLIENTE])
    REFERENCES [dbo].[CLIENTE]( [COD_CLIENTE] )
    ON DELETE Cascade
    ON UPDATE Cascade
GO;
-- -------------------------------------------------------------
-- CHANGE "ENABLED" OF "LINK "lnk_CLIENTE_PEDIDO" --------------
ALTER TABLE [dbo].[PEDIDO] NOCHECK CONSTRAINT [lnk_CLIENTE_PEDIDO]
GO;
-- CREATE LINK "lnk_FORMA_PAGAMENTO_PEDIDO" --------------------
ALTER TABLE [dbo].[PEDIDO]
    ADD CONSTRAINT [lnk_FORMA_PAGAMENTO_PEDIDO]
    FOREIGN KEY ([COD_FORMA_PAGAMENTO])
    REFERENCES [dbo].[FORMA_PAGAMENTO]( [COD_FORMA_PAGAMENTO] )
    ON DELETE Cascade
    ON UPDATE Cascade
GO;
-- -------------------------------------------------------------
-- CHANGE "ENABLED" OF "LINK "lnk_FORMA_PAGAMENTO_PEDIDO" ------
ALTER TABLE [dbo].[PEDIDO] NOCHECK CONSTRAINT [lnk_FORMA_PAGAMENTO_PEDIDO]
GO;
