# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-02 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import escolar.financeiro.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escolas', '0010_auto_20180102_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoEscola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('serie', models.CharField(blank=True, max_length=20, null=True, verbose_name='série')),
                ('curso', models.CharField(blank=True, max_length=120, null=True, verbose_name='curso')),
                ('matricula_nr', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nr da Matrícula')),
                ('data_assinatura', models.DateTimeField(blank=True, null=True, verbose_name='Data assinatura')),
                ('contrato', models.FileField(blank=True, null=True, upload_to=escolar.financeiro.models.escola_contrato_path)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='valor')),
                ('nr_parcela', models.PositiveSmallIntegerField(verbose_name='Nr de Parcelas')),
                ('matricula_valor', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor Matrícula')),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Desconto')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_matriculado', to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.Escola')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_pelo_aluno', to=settings.AUTH_USER_MODEL)),
                ('user_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro_contratoescola_created_by', to=settings.AUTH_USER_MODEL)),
                ('user_upd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro_contratoescola_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('aluno__nome',),
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
            },
        ),
    ]
