# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-18 01:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import escolar.financeiro.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20180118_0134'),
        ('escolas', '0011_auto_20180118_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoEscola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_upd', models.DateTimeField(default=django.utils.timezone.now)),
                ('serie', models.CharField(blank=True, max_length=20, null=True, verbose_name='série')),
                ('curso', models.CharField(blank=True, max_length=120, null=True, verbose_name='curso')),
                ('ano', models.SmallIntegerField()),
                ('matricula_nr', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nr da Matrícula')),
                ('data_assinatura', models.DateTimeField(blank=True, null=True, verbose_name='Data assinatura')),
                ('contrato', models.FileField(blank=True, null=True, upload_to=escolar.financeiro.models.escola_contrato_path)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='valor')),
                ('nr_parcela', models.PositiveSmallIntegerField(verbose_name='Nr de Parcelas')),
                ('vencimento', models.IntegerField(validators=[escolar.financeiro.models.validate_vencimento], verbose_name='Dia de Pagar')),
                ('matricula_valor', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor Matrícula')),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Desconto')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_aluno', to='core.Perfil')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.Escola')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_responsavel', to='core.Perfil')),
                ('user_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro_contratoescola_created_by', to=settings.AUTH_USER_MODEL)),
                ('user_upd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro_contratoescola_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'contratos',
                'ordering': ('aluno__nome',),
                'verbose_name': 'contrato',
            },
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_pag', models.DateField(blank=True, null=True)),
                ('valor_pag', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('efet', models.BooleanField(default=False)),
                ('observacao', models.TextField(verbose_name='Observacao')),
                ('tipo', models.SmallIntegerField(blank=True, null=True, verbose_name='Tipo')),
                ('nr_parcela', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nr de Parcelas')),
                ('nr_documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nr Documento')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.ContratoEscola')),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.Movimento')),
            ],
            options={
                'ordering': ('data_prevista',),
            },
        ),
    ]