# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-06 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoaluno',
            name='material_data_parcela_um',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data parcela material'),
        ),
        migrations.AddField(
            model_name='contratoaluno',
            name='material_parcelas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nr de Parcelas/ material'),
        ),
        migrations.AddField(
            model_name='contratoaluno',
            name='material_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='valor material'),
        ),
        migrations.AlterField(
            model_name='contratoaluno',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Desconto por pontualidade'),
        ),
    ]
