# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-02 17:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratoescola',
            options={'verbose_name': 'contrato', 'verbose_name_plural': 'contratos'},
        ),
        migrations.AddField(
            model_name='contratoescola',
            name='ano',
            field=models.SmallIntegerField(choices=[(2017, 2017), (2018, 2018), (2019, 2019)], default=2017, verbose_name='Ano'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contratoescola',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_aluno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contratoescola',
            name='date_add',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contratoescola',
            name='date_upd',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contratoescola',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_responsavel', to=settings.AUTH_USER_MODEL),
        ),
    ]
