# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-08 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_auto_20180107_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimento',
            name='data_nf',
        ),
        migrations.RemoveField(
            model_name='movimento',
            name='num_nf',
        ),
    ]
