# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-10 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_auto_20180205_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observacao'),
        ),
    ]
