# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-14 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0018_escola_municipio'),
        ('financeiro', '0003_auto_20180210_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Categoria')),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escolas.Escola')),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(choices=[(None, '--'), (2017, 2017), (2018, 2018), (2019, 2019)], verbose_name='Ano')),
                ('tem_desconto', models.BooleanField(default=False, verbose_name='tem desconto')),
                ('condicao_desconto', models.SmallIntegerField(blank=True, choices=[(None, '--'), (1, 'Pagamento até a data vencimento'), (2, 'Pagamento até determinado dia útil')], null=True, verbose_name='condição desconto')),
                ('dia_util', models.SmallIntegerField(blank=True, choices=[(None, '--'), (1, '1º'), (2, '2º'), (3, '3º'), (4, '4º'), (5, '5º'), (6, '6º'), (7, '7º'), (8, '8º'), (9, '9º'), (10, '10º'), (11, '11º'), (12, '12º')], null=True, verbose_name='dia útil')),
                ('multa', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='Multa por atraso mensalidade')),
                ('juros', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='juros por atraso mensalidade')),
                ('condicao_juros', models.SmallIntegerField(blank=True, choices=[(None, '--'), (1, 'Por dia'), (2, 'Por Mês')], null=True, verbose_name='condição desconto')),
                ('material_parcelas', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nr de Parcelas/ apostilas')),
                ('data_um_material', models.DateField(blank=True, null=True)),
                ('data_dois_material', models.DateField(blank=True, null=True)),
                ('data_tres_material', models.DateField(blank=True, null=True)),
                ('data_quatro_material', models.DateField(blank=True, null=True)),
                ('data_cinco_material', models.DateField(blank=True, null=True)),
                ('data_seis_material', models.DateField(blank=True, null=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.Escola')),
            ],
        ),
    ]
