# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-14 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_categoriapagamento_parametroscontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.CategoriaPagamento'),
        ),
        migrations.AlterField(
            model_name='parametroscontrato',
            name='condicao_juros',
            field=models.SmallIntegerField(blank=True, choices=[(None, '--'), (1, 'Por dia'), (2, 'Por Mês')], null=True, verbose_name='condição juros'),
        ),
        migrations.AlterField(
            model_name='parametroscontrato',
            name='juros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='juros por atraso mensalidade (%)'),
        ),
        migrations.AlterField(
            model_name='parametroscontrato',
            name='multa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Multa por atraso mensalidade (%)'),
        ),
    ]
