# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-19 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_auto_20180214_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoaluno',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Desconto por pontualidade (%)'),
        ),
        migrations.AlterField(
            model_name='parametroscontrato',
            name='data_cinco_material',
            field=models.DateField(blank=True, null=True, verbose_name='5ª parcela em'),
        ),
        migrations.AlterField(
            model_name='parametroscontrato',
            name='data_dois_material',
            field=models.DateField(blank=True, null=True, verbose_name='2ª parcela em'),
        ),
        migrations.AlterField(
            model_name='parametroscontrato',
            name='data_quatro_material',
            field=models.DateField(blank=True, null=True, verbose_name='4ª parcela em'),
        ),
        migrations.AlterField(
            model_name='parametroscontrato',
            name='data_seis_material',
            field=models.DateField(blank=True, null=True, verbose_name='6ª parcela em'),
        ),
        migrations.AlterField(
            model_name='parametroscontrato',
            name='data_tres_material',
            field=models.DateField(blank=True, null=True, verbose_name='3ª parcela em'),
        ),
        migrations.AlterField(
            model_name='parametroscontrato',
            name='data_um_material',
            field=models.DateField(blank=True, null=True, verbose_name='1ª parcela em'),
        ),
        migrations.AlterField(
            model_name='parametroscontrato',
            name='juros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Juros por atraso mensalidade (%)'),
        ),
    ]
