# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-20 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_auto_20180218_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratoaluno',
            name='material_data_parcela_um',
        ),
        migrations.AddField(
            model_name='contratoaluno',
            name='condicao_desconto',
            field=models.SmallIntegerField(blank=True, choices=[(None, '--'), (1, 'Pagamento até a data vencimento'), (2, 'Pagamento até determinado dia útil')], null=True, verbose_name='condição desconto'),
        ),
        migrations.AddField(
            model_name='contratoaluno',
            name='condicao_juros',
            field=models.SmallIntegerField(blank=True, choices=[(None, '--'), (1, 'Por dia'), (2, 'Por Mês')], null=True, verbose_name='condição juros'),
        ),
        migrations.AddField(
            model_name='contratoaluno',
            name='dia_util',
            field=models.SmallIntegerField(blank=True, choices=[(None, '--'), (1, '1º'), (2, '2º'), (3, '3º'), (4, '4º'), (5, '5º'), (6, '6º'), (7, '7º'), (8, '8º'), (9, '9º'), (10, '10º'), (11, '11º'), (12, '12º')], null=True, verbose_name='dia útil'),
        ),
        migrations.AddField(
            model_name='contratoaluno',
            name='juros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Juros por atraso mensalidade (%)'),
        ),
        migrations.AddField(
            model_name='contratoaluno',
            name='multa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Multa por atraso mensalidade (%)'),
        ),
        migrations.AddField(
            model_name='contratoaluno',
            name='tem_desconto',
            field=models.BooleanField(default=False, verbose_name='tem desconto'),
        ),
        migrations.AddField(
            model_name='parametroscontrato',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Desconto por pontualidade (%)'),
        ),
        migrations.AddField(
            model_name='parametroscontrato',
            name='matricula_valor',
            field=models.DecimalField(decimal_places=2, default=380, max_digits=7, verbose_name='Valor Matrícula'),
            preserve_default=False,
        ),
    ]
