# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import escolar.financeiro.models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_auto_20180219_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametroscontrato',
            name='vencimento',
            field=models.IntegerField(default=10, validators=[escolar.financeiro.models.validate_vencimento], verbose_name='Dia de Pagar'),
            preserve_default=False,
        ),
    ]
