# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-03 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_auto_20180225_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratoaluno',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='contratoaluno',
            name='serie',
        ),
    ]
