# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-03 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0022_auto_20180302_2137'),
        ('financeiro', '0010_auto_20180302_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoaluno',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escolas.Serie'),
        ),
    ]
