# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 00:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import escolar.financeiro.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0011_contratoaluno_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_upd', models.DateTimeField(default=django.utils.timezone.now)),
                ('ano', models.SmallIntegerField()),
                ('data_assinatura', models.DateTimeField(blank=True, null=True, verbose_name='Data assinatura')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='valor')),
                ('nr_parcela', models.PositiveSmallIntegerField(verbose_name='Nr de Parcelas')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=escolar.financeiro.models.escola_contrato_path)),
                ('vencimento', models.IntegerField(blank=True, null=True, validators=[escolar.financeiro.models.validate_vencimento], verbose_name='Dia de Pagar')),
                ('user_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro_contrato_created_by', to=settings.AUTH_USER_MODEL)),
                ('user_upd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro_contrato_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='pagamento',
            options={'ordering': ('data',)},
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='data_pag',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='contratoaluno',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='contratoaluno',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='contratoaluno',
            name='data_assinatura',
        ),
        migrations.RemoveField(
            model_name='contratoaluno',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='contratoaluno',
            name='date_upd',
        ),
        migrations.RemoveField(
            model_name='contratoaluno',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contratoaluno',
            name='nr_parcela',
        ),
        migrations.RemoveField(
            model_name='contratoaluno',
            name='user_add',
        ),
        migrations.RemoveField(
            model_name='contratoaluno',
            name='user_upd',
        ),
        migrations.RemoveField(
            model_name='contratoaluno',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='contratoaluno',
            name='vencimento',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='data_prevista',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='valor_pag',
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.Contrato'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='efet',
            field=models.BooleanField(default=False, verbose_name='pago:'),
        ),
        migrations.AddField(
            model_name='contratoaluno',
            name='contrato_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.Contrato'),
            preserve_default=False,
        ),
    ]
