# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_contratoaluno_bolsa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoaluno',
            name='material_parcelas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nr de Parcelas da apostila'),
        ),
        migrations.AlterField(
            model_name='contratoaluno',
            name='material_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='valor total das apostilas'),
        ),
        migrations.AlterField(
            model_name='parametroscontrato',
            name='material_parcelas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nr de Parcelas da apostilas'),
        ),
    ]
