# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0014_auto_20180501_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='observacao',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='rescindido',
            field=models.BooleanField(default=False),
        ),
    ]
