# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-02 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0016_categoriapagamento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='assinado',
            field=models.BooleanField(default=False, verbose_name='Assinado'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_assinatura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Matrícula'),
        ),
    ]
