# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-09 22:15
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0034_auto_20180507_2038'),
        ('financeiro', '0018_pagamento_forma_pgto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bandeira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('escola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escolas.Escola')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='BandeiraEscolaParametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=True)),
                ('taxa_debito', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Taxa no débto')),
                ('taxa_credito', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Taxa no crédito')),
                ('dias_debito', models.SmallIntegerField(blank=True, null=True, verbose_name='Dia(s) para receber no débto')),
                ('dias_credito', models.SmallIntegerField(blank=True, null=True, verbose_name='Dia(s) para receber no crédito')),
                ('bandeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Bandeira')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.Escola')),
            ],
            options={
                'verbose_name': 'Bandeira Paraâmetros',
                'verbose_name_plural': 'Bandeiras Paraâmetros',
            },
        ),
        migrations.AddField(
            model_name='pagamento',
            name='taxa_cartao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Taxa do cartão'),
        ),
        migrations.AlterField(
            model_name='parametroscontrato',
            name='ano',
            field=models.SmallIntegerField(choices=[(2018, 2018), (2019, 2019)], verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='bandeira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.Bandeira'),
        ),
        migrations.AlterUniqueTogether(
            name='bandeiraescolaparametro',
            unique_together=set([('escola', 'bandeira')]),
        ),
    ]
