# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-08-01 20:30
from __future__ import unicode_literals

from decimal import Decimal
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0019_auto_20180909_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='InadimplenteDBView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField()),
                ('pagamentos_atrasados', models.SmallIntegerField()),
                ('titulos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('multa', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('juros', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('cpf_resp_fin', models.CharField(max_length=11)),
                ('responsavel_nome', models.CharField(max_length=100)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('aluno_nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'view_inadimplentes',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='parametroscontrato',
            name='ano',
            field=models.SmallIntegerField(choices=[(2020, 2020), (2021, 2021)], verbose_name='Ano'),
        ),
    ]
