# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-09-05 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0021_auto_20200808_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'ordering': ('data_pag',)},
        ),
    ]
