# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2021-01-10 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0022_auto_20200905_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoaluno',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escolas.Serie'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='bandeira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.Bandeira'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.CategoriaPagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.Contrato'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='parcela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.Pagamento'),
        ),
        migrations.AlterField(
            model_name='parametroscontrato',
            name='ano',
            field=models.SmallIntegerField(choices=[(2021, 2021), (2022, 2022)], verbose_name='Ano'),
        ),
    ]
